apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ui-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: ui.application.txt
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: todo-ui-service
                port:
                  number: 80
