apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: firefox
  template:
    metadata:
      labels:
        app: firefox
    spec:
      containers:
        - name: firefox
          image: jlesage/firefox
          ports:
            - containerPort: 5800
